// get users paginated
GET http://localhost:3000/users?size=50&page=0&estado=Todos

###

// get users paginated
GET http://localhost:3000/users?size=25&page=0&filter=john&estado=Todos


###

// get one resource
GET http://localhost:3000/users/ac0d8b91-df26-4350-b3a6-7ae076c24d79


###

// get one resource
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "john89@hotmail.com",
    "password": "1234"
}

###

// get one resource
PUT http://localhost:3000/users/ac0d8b91-df26-4350-b3a6-7ae076c24d79
Content-Type: application/json

{
    "name": "john89@hotmail.com",
    "estado": "Inactivo"
}